#!/bin/bash

export PATH=/usr/bin:/bin

cd $PEGASUS_SUBMIT_DIR

# use a temp file for the message body
TMPFILE=`mktemp -t pegasus-notification.XXXXXXXXXX` || exit 1

cat >>$TMPFILE <<EOF
The workflow in:

  $PEGASUS_SUBMIT_DIR

Below is output from pegasus-status.

EOF

pegasus-status -v >>$TMPFILE 2>&1
echo >>$TMPFILE

EXTRA_ARGS=""

## workflow images in the start message (only for small workflows
JOBS=`ls *.sub | wc -l`
if [ $JOBS -lt 500 ]; then
    if [ ! -e dax.png ]; then
        pegasus-graphviz -o dag.dot *.dag
        dot -Tpng -odag.png dag.dot
        if [ -e dag.png ]; then
            EXTRA_ARGS="$EXTRA_ARGS -a dag.png"
        fi
    
        pegasus-graphviz -o dax.dot dax.xml
        dot -Tpng -odax.png dax.dot
        if [ -e dax.png ]; then
            EXTRA_ARGS="$EXTRA_ARGS -a dax.png"
        fi
    fi
fi

# grab the email from .forward for now
if [ -e ~/.forward ]; then
    for DEST in `cat ~/.forward | grep "@"`; do
        cat $TMPFILE | mailx -s "Workflow event: $PEGASUS_EVENT  $PEGASUS_SUBMIT_DIR" $EXTRA_ARGS $DEST
    done
fi

rm -f $TMPFILE

