#!/bin/bash

# module init required when running on non-OSG resources, and has to sourced
# before set -e as sometimes it exits non-0 when a module environment is 
# already set up
. /cvmfs/oasis.opensciencegrid.org/osg/sw/module-init.sh

set -e

module load jdk/8u141-b15-x
module load cufflinks/2.2.1-6

set -v

BASE_NAME=$1
GFF3=$2

cufflinks -o $BASE_NAME.cuff -G $GFF3 *.bam

cp $BASE_NAME.cuff/transcripts.gtf .

python GTF_parse.py transcripts.gtf > $BASE_NAME-fpkm
