#!/bin/bash

set -e

module load java/8u25
module load cufflinks/2.2.1

set -v

BASE_NAME=$1

cufflinks -o $BASE_NAME.cuff -G Mt4.0v1_genes_20130731_1800.gff3 *.bam

cp $BASE_NAME.cuff/transcripts.gtf .

python GTF_parse.py transcripts.gtf > $BASE_NAME-merged_counts.fpkm
