#!/bin/bash

. /cvmfs/oasis.opensciencegrid.org/osg/sw/module-init.sh

module load java/8u25
module load sra/2.5.4

set -e

SRA_ID=$1
FORWARD=$2

fastq-dump --gzip $SRA_ID

mv ${SRA_ID}.fastq.gz $FORWARD

echo
ls -lh
echo

