#!/bin/bash

. /cvmfs/oasis.opensciencegrid.org/osg/sw/module-init.sh

module load java/8u25
module load sra/2.5.4

set -e

SRA_ID=$1
FORWARD=$2
REVERSE=$3

fastq-dump --split-files --gzip $SRA_ID

mv ${SRA_ID}_1.fastq.gz $FORWARD
mv ${SRA_ID}_2.fastq.gz $REVERSE

echo
ls -lh
echo

