#!/bin/bash

# module init required when running on non-OSG resources, and has to sourced
# before set -e as sometimes it exits non-0 when a module environment is 
# already set up
. /cvmfs/oasis.opensciencegrid.org/osg/sw/module-init.sh

set -e

module load java/8u25
module load sra/2.5.4

SRA_ID=$1
FORWARD=$2

fastq-dump --gzip $SRA_ID

mv ${SRA_ID}.fastq.gz $FORWARD

echo
ls -lh
echo

